export default[
    {
       title:"Minutes Meeting",
       link:"/15Minutes-Meeting",
       duration:15,
       day:"Saturday",
       description:` Meet me in next 30 mins.`,
       type:'Business',
       with:"saqib",
       status:"On",
    },
    {
      title:"Minutes Meeting",
      link:"/30Minutes-Meeting",
      duration:30,
        day:"Saturday",
        description: "we will have a talk about our new project." ,
       type:'Discussion',
       with:"ahmed",
       status:"On",
     },
     {
        title:"Minutes Meeting",
        link:"/40Minutes-Meeting",
        duration:40,
        day:"Saturday",
        description: "School meeting." ,
       type:'Gupshup',
       with:"Ali",
       status:"Off",
     },
     {
        title:"Minutes Meeting",
        link:"/50Minutes-Meeting",
        duration:50,
        day:"Saturday",
        description: "Vacation workshop meeting" ,
       type:'Job',
       with:"Talha",
       status:"On",
     },
     {
        title:"Minutes Meeting",
        link:"/60Minutes-Meeting",
        duration:60,
        day:"Saturday",
        description: "Business Meeting" ,
       type:'School',
       with:"Shahmir",
       status:"Off",
     },

]