export default [
   {
      title: "Minutes Meeting",
      link: "/15Minutes-Meeting",
      duration: 15,
      day: "Saturday",
      description: ` Meet me in next 30 mins.`,
      with: "saqib",
      status: true,
   },
   {
      title: "Minutes Meeting",
      link: "/30Minutes-Meeting",
      duration: 30,
      day: "Saturday",
      description: "we will have a talk about our new project.",
      with: "ahmed",
      status: false,
   },
   {
      title: "Minutes Meeting",
      link: "/40Minutes-Meeting",
      duration: 40,
      day: "Saturday",
      description: "School meeting.",
      with: "Ali",
      status: false,
   },
   {
      title: "Minutes Meeting",
      link: "/50Minutes-Meeting",
      duration: 50,
      day: "Saturday",
      description: "Vacation workshop meeting",
      with: "Talha",
      status: true,
   },
   {
      title: "Minutes Meeting",
      link: "/60Minutes-Meeting",
      duration: 60,
      day: "Saturday",
      description: "Business Meeting",
      with: "Shahmir",
      status: false,
   },
]